import { TemplateDefinition } from './template-definition.types';

export const CLASSIC_LETTER_DEFINITION: TemplateDefinition = {
  themeCode: 'CLASSIC_LETTER',
  schemaVersion: 1,
  contentFields: [
    {
      key: 'partnerOneName',
      label: 'Nama Pasangan 1',
      type: 'text',
      required: true,
      maxLength: 60,
    },
    {
      key: 'partnerTwoName',
      label: 'Nama Pasangan 2',
      type: 'text',
      required: true,
      maxLength: 60,
    },
    {
      key: 'partnerOneFullName',
      label: 'Nama Lengkap Pasangan 1',
      type: 'text',
      maxLength: 120,
    },
    {
      key: 'partnerTwoFullName',
      label: 'Nama Lengkap Pasangan 2',
      type: 'text',
      maxLength: 120,
    },
    {
      key: 'partnerOneFamily',
      label: 'Keluarga Pasangan 1',
      type: 'textarea',
      maxLength: 300,
    },
    {
      key: 'partnerTwoFamily',
      label: 'Keluarga Pasangan 2',
      type: 'textarea',
      maxLength: 300,
    },
    {
      key: 'timeZone',
      label: 'Zona Waktu',
      type: 'select',
      required: true,
      options: [
        { label: 'WIB', value: 'Asia/Jakarta' },
        { label: 'WITA', value: 'Asia/Makassar' },
        { label: 'WIT', value: 'Asia/Jayapura' },
      ],
    },
    {
      key: 'intro',
      label: 'Teks Pembuka',
      type: 'textarea',
      maxLength: 600,
    },
    {
      key: 'quote',
      label: 'Kutipan Cinta',
      type: 'textarea',
      maxLength: 400,
    },
    {
      key: 'prayer',
      label: 'Teks Doa',
      type: 'textarea',
      maxLength: 600,
    },
    {
      key: 'closing',
      label: 'Teks Penutup',
      type: 'textarea',
      maxLength: 400,
    },
    {
      key: 'ceremonies',
      label: 'Rangkaian Acara',
      type: 'repeater',
      maxItems: 2,
      fields: [
        {
          key: 'title',
          label: 'Nama Acara',
          type: 'text',
          required: true,
          maxLength: 80,
        },
        {
          key: 'startDateTime',
          label: 'Waktu Mulai',
          type: 'datetime',
          required: true,
        },
        {
          key: 'endDateTime',
          label: 'Waktu Selesai',
          type: 'datetime',
        },
        {
          key: 'venue',
          label: 'Tempat Acara',
          type: 'text',
          required: true,
          maxLength: 150,
        },
        {
          key: 'address',
          label: 'Alamat Acara',
          type: 'textarea',
          maxLength: 500,
        },
        {
          key: 'mapsUrl',
          label: 'Tautan Google Maps',
          type: 'url',
          urlPolicy: 'google-maps',
          maxLength: 2048,
        },
      ],
    },
    {
      key: 'giftAccounts',
      label: 'Rekening Hadiah',
      type: 'repeater',
      maxItems: 2,
      fields: [
        {
          key: 'bankName',
          label: 'Nama Bank',
          type: 'text',
          required: true,
          maxLength: 100,
        },
        {
          key: 'accountNumber',
          label: 'Nomor Rekening',
          type: 'text',
          required: true,
          maxLength: 50,
        },
        {
          key: 'accountHolder',
          label: 'Nama Pemilik Rekening',
          type: 'text',
          required: true,
          maxLength: 120,
        },
      ],
    },
  ],
  mediaSlots: [
    {
      key: 'bg-photo',
      label: 'Foto Background',
      mediaType: 'PHOTO',
      multiple: false,
      maxItems: 1,
      maxSizeBytes: 5 * 1024 * 1024,
    },
    {
      key: 'bg-video',
      label: 'Video Background',
      mediaType: 'VIDEO',
      multiple: false,
      maxItems: 1,
      maxSizeBytes: 20 * 1024 * 1024,
    },
    {
      key: 'bg-poster',
      label: 'Poster Video Background',
      mediaType: 'PHOTO',
      multiple: false,
      maxItems: 1,
      maxSizeBytes: 5 * 1024 * 1024,
    },
    {
      key: 'couple-photo',
      label: 'Foto Pasangan',
      mediaType: 'PHOTO',
      multiple: false,
      maxItems: 1,
      maxSizeBytes: 5 * 1024 * 1024,
    },
    {
      key: 'gallery',
      label: 'Galeri Foto',
      mediaType: 'PHOTO',
      multiple: true,
      maxItems: 2,
      maxSizeBytes: 5 * 1024 * 1024,
    },
  ],
};
