import { TemplateDefinition } from './template-definition.types';

export const VELVET_LETTER_DEFINITION: TemplateDefinition = {
  themeCode: 'VELVET_LETTER',
  schemaVersion: 1,
  contentFields: [
    {
      key: 'partnerOneName',
      label: 'Nama Pasangan 1',
      type: 'text',
      required: true,
      maxLength: 50,
    },
    {
      key: 'partnerTwoName',
      label: 'Nama Pasangan 2',
      type: 'text',
      required: true,
      maxLength: 50,
    },
    {
      key: 'partnerOneFullName',
      label: 'Nama Lengkap Pasangan 1',
      type: 'text',
      maxLength: 100,
    },
    {
      key: 'partnerTwoFullName',
      label: 'Nama Lengkap Pasangan 2',
      type: 'text',
      maxLength: 100,
    },
    {
      key: 'partnerOneFamily',
      label: 'Keluarga Pasangan 1',
      type: 'textarea',
      maxLength: 300,
    },
    {
      key: 'partnerTwoFamily',
      label: 'Keluarga Pasangan 2',
      type: 'textarea',
      maxLength: 300,
    },
    {
      key: 'timeZone',
      label: 'Zona Waktu',
      type: 'select',
      required: true,
      options: [
        { label: 'WIB', value: 'Asia/Jakarta' },
        { label: 'WITA', value: 'Asia/Makassar' },
        { label: 'WIT', value: 'Asia/Jayapura' },
      ],
    },
    {
      key: 'intro',
      label: 'Teks Pembuka',
      type: 'textarea',
      maxLength: 1500,
    },
    {
      key: 'prayer',
      label: 'Teks Doa',
      type: 'textarea',
      maxLength: 2000,
    },
    {
      key: 'closing',
      label: 'Teks Penutup',
      type: 'textarea',
      maxLength: 1200,
    },
    {
      key: 'giftMessage',
      label: 'Pesan Hadiah',
      type: 'textarea',
      maxLength: 1000,
    },
    {
      key: 'ceremonies',
      label: 'Rangkaian Acara',
      type: 'repeater',
      maxItems: 2,
      fields: [
        {
          key: 'title',
          label: 'Nama Acara',
          type: 'text',
          required: true,
          maxLength: 60,
        },
        {
          key: 'startDateTime',
          label: 'Waktu Mulai',
          type: 'datetime',
          required: true,
        },
        {
          key: 'endDateTime',
          label: 'Waktu Selesai',
          type: 'datetime',
        },
        {
          key: 'venue',
          label: 'Tempat Acara',
          type: 'text',
          required: true,
          maxLength: 150,
        },
        {
          key: 'address',
          label: 'Alamat Acara',
          type: 'textarea',
          maxLength: 400,
        },
        {
          key: 'mapsUrl',
          label: 'Tautan Google Maps',
          type: 'url',
          urlPolicy: 'google-maps',
          maxLength: 2048,
        },
      ],
    },
    {
      key: 'giftAccounts',
      label: 'Rekening Hadiah',
      type: 'repeater',
      maxItems: 2,
      fields: [
        {
          key: 'bankName',
          label: 'Nama Bank / Layanan',
          type: 'text',
          required: true,
          maxLength: 60,
        },
        {
          key: 'accountNumber',
          label: 'Nomor Rekening',
          type: 'text',
          required: true,
          maxLength: 40,
        },
        {
          key: 'accountHolder',
          label: 'Nama Pemilik Rekening',
          type: 'text',
          required: true,
          maxLength: 100,
        },
      ],
    },
  ],
  mediaSlots: [
    {
      key: 'partner-one-photo',
      label: 'Foto Mempelai 1',
      mediaType: 'PHOTO',
      multiple: false,
      maxItems: 1,
      maxSizeBytes: 5 * 1024 * 1024,
    },
    {
      key: 'partner-two-photo',
      label: 'Foto Mempelai 2',
      mediaType: 'PHOTO',
      multiple: false,
      maxItems: 1,
      maxSizeBytes: 5 * 1024 * 1024,
    },
  ],
};
